WITH cleaned_trips AS (
    SELECT
        VENDORID,
        TO_TIMESTAMP_NTZ(TPEP_PICKUP_DATETIME / 1000000) AS TPEP_PICKUP_DATETIME,
        TO_TIMESTAMP_NTZ(TPEP_DROPOFF_DATETIME / 1000000) AS TPEP_DROPOFF_DATETIME,
        PASSENGER_COUNT,
        TRIP_DISTANCE,
        RATECODEID,
        CAST(STORE_AND_FWD_FLAG AS BOOLEAN) AS STORE_AND_FWD_FLAG,
        PULOCATIONID,
        DOLOCATIONID,
        PAYMENT_TYPE,
        FARE_AMOUNT,
        EXTRA,
        MTA_TAX,
        TIP_AMOUNT,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        TOTAL_AMOUNT,
        CONGESTION_SURCHARGE,
        AIRPORT_FEE,
        CBD_CONGESTION_FEE
    FROM {{ source('raw_tb', 'YELLOW_TAXI_TRIPS') }}
    WHERE 
        TPEP_DROPOFF_DATETIME > TPEP_PICKUP_DATETIME
        AND TRIP_DISTANCE IS NOT NULL AND TRIP_DISTANCE BETWEEN 0.1 AND 100
        AND PULOCATIONID IS NOT NULL
        AND DOLOCATIONID IS NOT NULL
        AND TIP_AMOUNT >= 0
        AND FARE_AMOUNT >= 0
        AND TOTAL_AMOUNT >= 0
)
SELECT 
    *,
    MONTH(TPEP_PICKUP_DATETIME) AS PICKUP_MONTH,
    DAY(TPEP_PICKUP_DATETIME) AS PICKUP_DAY,
    HOUR(TPEP_PICKUP_DATETIME) AS PICKUP_HOUR
FROM cleaned_trips