WITH trip_counts AS (
  SELECT
    PULOCATIONID,
    COUNT(*) AS VOLUME,
    (TOTAL_AMOUNT / VOLUME) AS AVERAGE_ACCOUNT
  FROM {{ ref('int_trip_metrics') }}
  GROUP BY PULOCATIONID
)
SELECT
    PULOCATIONID,
    VOLUME,
    AVERAGE_ACCOUNT,
    DENSE_RANK() OVER (ORDER BY VOLUME DESC) AS POPULARITY
FROM trip_counts


    -- VENDORID,
    -- TPEP_PICKUP_DATETIME,
    -- TPEP_DROPOFF_DATETIME,
    -- TEMPORAL_PERIOD,
    -- DAY_TYPE,
    -- DURATION,
    -- PASSENGER_COUNT,
    -- TRIP_DISTANCE,
    -- DISTANCE_CATEGORY,
    -- RATECODEID,
    -- STORE_AND_FWD_FLAG,
    -- PULOCATIONID,
    -- DOLOCATIONID,
    -- PAYMENT_TYPE,
    -- FARE_AMOUNT,
    -- EXTRA,
    -- MTA_TAX,
    -- TIP_AMOUNT,
    -- TIP_PART,
    -- TOLLS_AMOUNT,
    -- IMPROVEMENT_SURCHARGE,
    -- TOTAL_AMOUNT,
    -- CONGESTION_SURCHARGE,
    -- AIRPORT_FEE,
    -- CBD_CONGESTION_FEE
    -- AVERAGE_SPEED